using HarborConnect.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HarborConnect.Controllers
{
    [Authorize]
    public class BoatController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Boat/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(
                db.BoatCategories,
                "CategoryId",
                "CategoryName"
            );

            return View();
        }

        // POST: Boat/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Boat boat)
        {
            // These values are generated by the system,
            // not entered by the boat owner.
            boat.OwnerId = User.Identity.GetUserId();
            boat.Status = "Unavailable";
            boat.ApprovalStatus = "Pending";
            boat.CreatedDate = DateTime.Now;

            // Remove validation errors for fields that are
            // automatically generated by the system.
            ModelState.Remove("OwnerId");
            ModelState.Remove("Status");
            ModelState.Remove("ApprovalStatus");
            ModelState.Remove("CreatedDate");

            if (ModelState.IsValid)
            {
                db.Boats.Add(boat);

                await db.SaveChangesAsync();

                return RedirectToAction("MyBoats");
            }

            // If something else is wrong, show the form again.
            ViewBag.CategoryId = new SelectList(
                db.BoatCategories,
                "CategoryId",
                "CategoryName",
                boat.CategoryId
            );

            return View(boat);
        }


        // GET: Boat/MyBoats
        public async Task<ActionResult> MyBoats()
        {
            string ownerId = User.Identity.GetUserId();

            var boats = await db.Boats
                .Include(b => b.Category)
                .Where(b => b.OwnerId == ownerId)
                .OrderByDescending(b => b.CreatedDate)
                .ToListAsync();

            return View(boats);
        }

        // ==========================================
        // ADMIN BOAT APPROVAL DASHBOARD
        // ==========================================

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Approval()
        {
            var boats = await db.Boats
                .Include(b => b.Category)
                .Include(b => b.Owner)
                .Where(b => b.ApprovalStatus == "Pending")
                .OrderByDescending(b => b.CreatedDate)
                .ToListAsync();

            return View(boats);
        }


        // ==========================================
        // APPROVE BOAT
        // ==========================================

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Approve(int id)
        {
            var boat = await db.Boats.FindAsync(id);

            if (boat == null)
            {
                return HttpNotFound();
            }

            boat.ApprovalStatus = "Approved";
            boat.Status = "Available";
            boat.ApprovedDate = DateTime.Now;

            await db.SaveChangesAsync();

            return RedirectToAction("Approval");
        }


        // ==========================================
        // REJECT BOAT
        // ==========================================

        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reject(int id, string adminComment)
        {
            var boat = await db.Boats.FindAsync(id);

            if (boat == null)
            {
                return HttpNotFound();
            }

            boat.ApprovalStatus = "Rejected";
            boat.Status = "Unavailable";
            boat.AdminComment = adminComment;

            await db.SaveChangesAsync();

            return RedirectToAction("Approval");
        }


        // ==========================================
        // DISPOSE
        // ==========================================

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }


       
    }
}